backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: images # required but unused, host images externally
collections:
  - name: "case_studies"
    label: "Case Studies"
    label_singular: "Case Study"
    folder: "source/_case_study"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Type", name: "type", widget: "string", required: true}
      - {label: "Image Filename", name: "image", widget: "string", required: false}
      - {label: "Write Up", name: "writeup", widget: "markdown", required: false}
