backend:
  name: git-gateway
  branch: master
  squash_merges: true
media_folder: "/build/source/assets/images/"
public_folder: "/assets/build/images/"
# logo_url: https://thelonious.com.au/images/logo.svg
collections:
  - name: "case_studies"
    label: "Case Studies"
    label_singular: "Case Study"
    folder: "source/_casestudies"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Type", name: "type", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "date", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Write Up", name: "writeup", widget: "markdown", required: false}
